name: developer
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  developer:
    runs-on: ubuntu-latest
    env: 
      FC: gfortran-11
      CC: gcc-11
        
    steps:

    - name: checkout-wrf_io
      uses: actions/checkout@v4
      with: 
        path: wrf_io

    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz libnetcdf-dev libnetcdff-dev

    - name: build_wrf_io
      run: |
        set -x
        cmake -S wrf_io -B wrf_io/build -DENABLE_DOCS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_FLAGS="-g -fprofile-abs-path -fprofile-arcs -ftest-coverage -O0 -Wall -fsanitize=address" ..
        cmake --build wrf_io/build --verbose
