name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]
      
    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}

    - name: checkout-wrf_io
      uses: actions/checkout@v4
      with: 
        path: wrf_io

    - name: build_wrf_io
      run: |
        cmake -S wrf_io -B wrf_io/build
        cmake --build wrf_io/build --verbose
