name: Linux
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux:
    runs-on: ubuntu-latest
    env: 
      FC: gfortran-11
      CC: gcc-11
    steps:

    - name: checkout-wrf_io
      uses: actions/checkout@v4
      with: 
        path: wrf_io

    - name: Installs
      run: |
        sudo apt-get install libnetcdf-dev libnetcdff-dev

    - name: build_wrf_io
      run: |
        cmake -S wrf_io -B wrf_io/build
        cmake --build wrf_io/build --verbose

