name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc-12

    steps:

    - name: checkout-wrf_io
      uses: actions/checkout@v4
      with: 
        path: wrf_io
    
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        brew update
        brew install netcdf netcdf-fortran

    - name: build_wrf_io
      run: |
        cmake -S wrf_io -B wrf_io/build
        cmake --build wrf_io/build --verbose

