name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc

    steps:

    - name: checkout-wrf_io
      uses: actions/checkout@v2
      with: 
        path: wrf_io
    
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        brew update
        brew install netcdf netcdf-fortran

    - name: build_wrf_io
      run: |
        set -x
        cd wrf_io
        mkdir build 
        cd build
        cmake ..
        make VERBOSE=1
