name: MacOS
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc

    steps:
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        brew update
        brew install netcdf netcdf-fortran

    - name: build_wrf_io
      run: |
        set -x
        cd NCEPLIBS-wrf_io
        mkdir build 
        cd build
        cmake ..
        make VERBOSE=1
