# This is a CI workflow for the NCEPLIBS-wrf_io project.
#
# This workflow builds wrf_io with Spack. It also has a one-off job that
# validates the recipe by ensuring that every CMake option that should be set
# in the Spack recipe is so set.
#
# Alex Richert, Nov 2023
name: Spack
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Spack:
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    
    - name: "Build Spack package"
      uses: NOAA-EMC/ci-test-spack-package@develop
      with:
        package-name: wrf-io
        package-variants: "^netcdf-c ~blosc ~szip ~mpi ^hdf5~mpi"
        custom-recipe: spack/package.py
        use-repo-cache: true
        spack-compiler: gcc
        repo-cache-key-suffix: ${{ matrix.os }}-1
        spack-externals: cmake gmake perl openmpi

  # This job validates the Spack recipe by making sure each cmake build option is represented
  recipe-check:
    runs-on: ubuntu-latest

    steps:

    - name: recipe-check
      uses: NOAA-EMC/ci-check-spack-recipe@develop
      with:
        recipe-file: package/spack/package.py
        cmakelists-txt: package/CMakeLists.txt
        ignore-list: ENABLE_DOCS
